"""Agregar campos de origen, cobertura y promocion con opcion otros

Revision ID: bf490a780713
Revises: 
Create Date: 2025-06-06 18:08:10.520055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf490a780713'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen_otro', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('cobertura_actual_otra', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('promocion', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('promocion_otra', sa.String(length=128), nullable=True))
        batch_op.alter_column('origen',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('cobertura_actual',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.alter_column('cobertura_actual',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('origen',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('promocion_otra')
        batch_op.drop_column('promocion')
        batch_op.drop_column('cobertura_actual_otra')
        batch_op.drop_column('origen_otro')

    # ### end Alembic commands ###
