"""actualizar campos del formulario y agregar conyuge

Revision ID: f2c9f7059180
Revises: b65bc4d4bc3d
Create Date: 2025-07-01 22:11:27.712528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c9f7059180'
down_revision = 'b65bc4d4bc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        # Agregar columnas como nullable primero
        batch_op.add_column(sa.Column('conyuge', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('conyuge_edad', sa.String(length=32), nullable=True))
        
    # Actualizar datos existentes
    op.execute("UPDATE contacto SET conyuge = 'Sin cónyuge' WHERE conyuge IS NULL")
    
    # Hacer la columna conyuge NOT NULL
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.alter_column('conyuge', nullable=False)
        batch_op.drop_column('promocion_otra')
        batch_op.drop_column('origen_otro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen_otro', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('promocion_otra', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('conyuge_edad')
        batch_op.drop_column('conyuge')

    # ### end Alembic commands ###
